#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid

source /etc/cron.daily/prelink
ln -sf /usr/share/images/desktop-base/xanadu-wallpaper_1280x1024.svg /usr/share/images/desktop-base/joy-wallpaper_1280x1024.svg
ln -sf /usr/share/images/desktop-base/xanadu-grub.png /usr/share/images/desktop-base/desktop-grub.png
update-alternatives --install /etc/alternatives/desktop-background wall-2 /usr/share/images/desktop-base/xanadu-wallpaper_1280x1024.svg 90
update-alternatives --install /usr/share/images/desktop-base/login-background.svg wall-3 /usr/share/images/desktop-base/xanadu-wallpaper_1280x1024.svg 90
update-alternatives --install /usr/share/images/desktop-base/random/joy-wallpaper_1280x1024.svg wall-4 /usr/share/images/desktop-base/xanadu-wallpaper_1280x1024.svg 90
update-alternatives --install /usr/share/images/desktop-base/joy-grub.png wall-5 /usr/share/images/desktop-base/xanadu-grub.png 90
rm -f /usr/share/applications/clamtk.desktop
rm -rf /var/cache/apt/*
rm -rf /var/cache/apt/archives/*

rm -f /run/$(basename $0).pid
exit 0
